@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNGZ0dXdEFSUmVPVEpuZk1wMHd3ZCJ9.eyJpc3MiOiJodHRwczovL2NsdWJlcm8udXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDY4ZjI1Yjg4M2E1NjcwNWViYmM0MGI5YyIsImF1ZCI6WyJjbHViZXJvLWFwaSIsImh0dHBzOi8vY2x1YmVyby51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzYyNDM1MzM5LCJleHAiOjE3NjI1MjE3MzksInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhenAiOiIydjNPcDdNMW9oZDJDU0xHaXkxd3YwUDdlRnpJc2JrWSIsInBlcm1pc3Npb25zIjpbImNyZWF0ZTpjbHViIiwicmVhZDpjbHViIiwidXBkYXRlOmNsdWIiXX0.QfXDipjhf26zu9dvqllJI2zDd-E7jpHlG1o7YL8WpHND5-8HLSGT8k83knJjuC3CylIRZ8j67cKCcsJDx2RwnSAguVDThgVllYAHSEzQ_4LZ06lk4nof5v-ZUEowJaGwQhuwPmMGgghk7SYhdPolpxdK03gc57a1Ybg2PgeiSZiv9-au1WITvGze579hzZMLzdIOZi8gcFoP8CXWFUlYYNCuCRwqmdUCi-GTLkEE0yron2fMUNcJQoLjMo40hbak_u7wOzz21Y6e5KbSh8TzrtqkAeu3rikZKnsQAyZQYMrUZUKWTw_9yg-Nu76YIkU77nsKhTTIbfMPZ2DpIGLRYg

### Get all clubs
GET http://localhost:3030/api/clubs/all
Authorization: Bearer {{ token }}

### Get all clubs
GET http://localhost:3030/api/clubs 
Authorization: Bearer {{ token }}

### Get user by ID
GET http://localhost:3030/api/club/1 
Authorization: Bearer {{ token }}


### Create a new Club
POST http://localhost:3030/api/club
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "name": "Clubero FC",
    "description": "El mejor club del mundo",
    "image": "https://clubero.com/logo.png",
    "country": "Argentina",
    "state": "Buenos Aires",
    "city": "La Plata",
    "founded": "1901-01-01T00:00:00Z",
    "active": true
}

### Update user by ID
PUT http://localhost:3030/api/club/1
Authorization: Bearer {{ token }}
Content-Type: application/json

{
    "name": "Crimson Fox",
    "description": "El mejor club del mundo",
    "image": "https://clubero.com/logo.png",
    "country": "Brasil",
    "state": "São Paulo",
    "city": "São Paulo",
    "founded": "2017-01-01T00:00:00Z",
    "active": true
}


### Delete user by ID
DELETE http://localhost:3030/api/club/2
Authorization: Bearer {{ token }}

