@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNGZ0dXdEFSUmVPVEpuZk1wMHd3ZCJ9.eyJpc3MiOiJodHRwczovL2NsdWJlcm8udXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDY4ZjI1Yjg4M2E1NjcwNWViYmM0MGI5YyIsImF1ZCI6WyJjbHViZXJvLWFwaSIsImh0dHBzOi8vY2x1YmVyby51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzYzNTg3NjE5LCJleHAiOjE3NjM2NzQwMTksInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhenAiOiIydjNPcDdNMW9oZDJDU0xHaXkxd3YwUDdlRnpJc2JrWSIsInBlcm1pc3Npb25zIjpbImFkbWluIiwiY3JlYXRlOmNsdWIiLCJyZWFkOmNsdWIiLCJ1cGRhdGU6Y2x1YiJdfQ.uauFZZP9CWZq6qHCplyiMFziBnD4FQqlZLAG8CcgKXh-QExnAOjxRj99u6oWixuuzIA7J5wt8K9KVh8cY_btu1gNl0Z-HuElFUStwf47Xg2M7qjrrmQbY0RqknGPH7P7HpV5igOB4pajuzhrNSDB1nH_ARuwjtSgMQ7WQgtBy1yUSJc0zl4MW9VnHuZ3MUWlqZL3MSLSYqJM89S9IqXcXLDxkvBQ71NC9zEhQ2HCovtnWlM_e4_wC2XmwX-tfxqpsDFSCUXYZGB26H6jupAoktVOXkFtmD0k_epQE071MENzXfq3q3DzecImDq9O4EoAiYGzHyCnynT88LY23owADQ

@baseUrl = http://localhost:3030/api


### Get all clubs
GET http://localhost:3030/api/clubs/all
Authorization: Bearer {{ token }}

### Get all clubs
GET http://localhost:3030/api/clubs 
Authorization: Bearer {{ token }}

### Get user by ID
GET http://localhost:3030/api/club/1 
Authorization: Bearer {{ token }}


### Create a new Club
POST http://localhost:3030/api/club
Content-Type: application/json
Authorization: Bearer {{ token }}

{
    "name": "Crimson Fox",
    "description": "Melhor Clube de Flag Footbal de São Paulo",
    "image": "",
    "country": "Brasil",
    "state": "SP",
    "city": "São Paulo",
    "founded": "2017-09-01T00:00:00Z",
    "active": true
}

### Update user by ID
PUT http://localhost:3030/api/club/1
Authorization: Bearer {{ token }}
Content-Type: application/json

{
    "name": "Crimson Fox",
    "description": "El mejor club del mundo",
    "image": "https://clubero.com/logo.png",
    "country": "Brasil",
    "state": "São Paulo",
    "city": "São Paulo",
    "founded": "2017-01-01T00:00:00Z",
    "active": true
}


### Delete user by ID
DELETE http://localhost:3030/api/club/2
Authorization: Bearer {{ token }}

