@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNGZ0dXdEFSUmVPVEpuZk1wMHd3ZCJ9.eyJpc3MiOiJodHRwczovL2NsdWJlcm8udXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDY4ZjI1Yjg4M2E1NjcwNWViYmM0MGI5YyIsImF1ZCI6WyJjbHViZXJvLWFwaSIsImh0dHBzOi8vY2x1YmVyby51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzYzMTM5NzAzLCJleHAiOjE3NjMyMjYxMDMsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhenAiOiIydjNPcDdNMW9oZDJDU0xHaXkxd3YwUDdlRnpJc2JrWSIsInBlcm1pc3Npb25zIjpbImFkbWluIiwiY3JlYXRlOmNsdWIiLCJyZWFkOmNsdWIiLCJ1cGRhdGU6Y2x1YiJdfQ.kstbjTRjaNtFII_utQ1BtNqqSFdF3tuIgiphtWeQvg_hwEAyTHjsDEW5TnLgWI1rhAr08udsiYv8k8HZ2VRNQcRd7qDcarUCIJq7IJsnIUdT3FvlKqqYT9d430kxZY-LKJk8ugJhhWeJkOS1Zyhbr_HAHBJUI_B_3EsMdmdM9sPZA5FQ7NPI6j0xsOWo7LsczPkZYeRCs2AG7jpTmx255S3APSzCDWEulaH48E9Jy_J9YjZTMZsivKzqEeOSAck5Pwu0-eik1GtNbOi8zeKsiSA90L9_mwHrgHZubuZbTZPcWXJPFZxptQXSVvWjpX42TctmNsdPbrTvbuC_bQ-axQ
@baseUrl = http://localhost:3030/api


GET http://localhost:3030/api/sports/all
Authorization: Bearer {{token}}

### Get sport by ID
GET http://localhost:3030/api/sport/1
Authorization: Bearer {{token}}

### Create a new sport
POST http://localhost:3030/api/sport
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Flag Football",
    "image": "http://example.com/soccer.png"
}

### Update sport by ID
PUT http://localhost:3030/api/sport/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Flag Football",
    "image": "http://example.com/flagfootball.png"
}

### Delete sport by ID
DELETE http://localhost:3030/api/sport/3
Authorization: Bearer {{token}}
