### Teams API tests
@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNGZ0dXdEFSUmVPVEpuZk1wMHd3ZCJ9.eyJpc3MiOiJodHRwczovL2NsdWJlcm8udXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDY4ZjI1Yjg4M2E1NjcwNWViYmM0MGI5YyIsImF1ZCI6WyJjbHViZXJvLWFwaSIsImh0dHBzOi8vY2x1YmVyby51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzYxOTM0NTc0LCJleHAiOjE3NjIwMjA5NzQsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhenAiOiIydjNPcDdNMW9oZDJDU0xHaXkxd3YwUDdlRnpJc2JrWSIsInBlcm1pc3Npb25zIjpbImNyZWF0ZTpjbHViIiwicmVhZDpjbHViIiwidXBkYXRlOmNsdWIiXX0.pOTP5SP_uONzm_e2aORhQ0CQiEDUD8sBP9zww95cFWeNwg_1eVT4XOCSEWKoark-yTzAPwXoYsqMKb8BqVC8djrVVHw6OypcDdigyVprA2xHACe7mILlMDz9SN6H32b4H_2HMX6_06zP9AsdTOan7pHJzx6ygCEi8_Z-ICo6iECAkKDCnsOR93MWT3HOx3qyEAJoYhlybWcETL9JJuZSc6GyhSVY79414PQ3YToDe1zSgfnxSSqtW2ypG4kWIAwahKmSgXikUMfDG0o0GJwsAWPiQIUznsnEk_rVWQdq1uRvF-EJ-3iZw7IS8RWFd_lOAZGk7rG3CO2-ITMaF1C9Rg

# Get all teams (unfiltered)
GET http://localhost:3030/api/teams/all
Authorization: Bearer {{token}}

###
# Get teams by current user
GET http://localhost:303/api/teams
Authorization: Bearer {{token}}

###
# Get a team by id
GET http://localhost:3030/api/team/1
Authorization: Bearer {{token}}

###
# Create a team
POST http://localhost:3030/api/team
Content-Type: application/json
Authorization: Bearer {{token}}

{
	"clubId": 1,
	"sportId": 2,
	"name": "Adulto Masculino",
	"gender": "MALE",
	"category": "Adulto",
	"active": true	
}

###
# Update a team
PUT http://localhost:3030/api/team/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
	"sportId": 1,
	"name": "Adulto Feminino",
	"description": "Time feminino adulto de Futebol Americano",
	"image": null,
	"gender": "FEMALE",
	"category": "Adulto",
	"active": true

}

###
# Delete a team
DELETE http://localhost:3030/api/team/1
Authorization: Bearer {{token}}
