
@token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNGZ0dXdEFSUmVPVEpuZk1wMHd3ZCJ9.eyJpc3MiOiJodHRwczovL2NsdWJlcm8udXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDY4ZjI1Yjg4M2E1NjcwNWViYmM0MGI5YyIsImF1ZCI6WyJjbHViZXJvLWFwaSIsImh0dHBzOi8vY2x1YmVyby51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzYyODc1MDIwLCJleHAiOjE3NjI5NjE0MjAsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhenAiOiIydjNPcDdNMW9oZDJDU0xHaXkxd3YwUDdlRnpJc2JrWSIsInBlcm1pc3Npb25zIjpbImFkbWluIiwiY3JlYXRlOmNsdWIiLCJyZWFkOmNsdWIiLCJ1cGRhdGU6Y2x1YiJdfQ.uWF3Vi_7GcqxOtpLypv9oi7lFRKJ0bwFqe0Lg30ce9ipjjFHJmWMAMjoS0w3KYSo4drCHEMZ21-Ej78kxXXNdnR2GFKRQ4UYK9uH1QW_Nr3DbtaAMmUViYim7D0oDKz36Qk1Js_iGbysHS7qcClQPIZr0lDtFK1iOQwUrrx-JYmnHw59zKJipWr7rlxrezehAb_I45y-Vl9LvnxZlHQLbfehyxXG9G7-9hDsbIhXoiF6QX1UMnMhEJkb0_-rp91n4Z3EDJq8fJzwrIWW-ZjdrSxnEfVO7T3DwlHK5Luqcio0bqXztfIo44CoIJBUZ9CKCGnvAfcua3Stkfvbh1Kfnw

### Teams API tests
GET http://localhost:3030/api/teams/all
Authorization: Bearer {{token}}

###
# Get teams CreateBy current user
GET http://localhost:3030/api/teams
Authorization: Bearer {{token}}

###
# Get teams by current user
GET http://localhost:3030/api/user/teams
Authorization: Bearer {{token}}


###
# Get a team by id
GET http://localhost:3030/api/team/2
Authorization: Bearer {{token}}

###
# Invite Users 
POST  http://localhost:3030/api/team/2/invite
Content-Type: application/json
Authorization: Bearer {{token}}


{
	"users": [
	{
		"name":"Anderson Peter",
		"nickname":"Peter",
		"email":"ltesta+peter@gmail.com"
	}]
}	






###
# Get a team by id with users
GET http://localhost:3030/api/team/2/users
Authorization: Bearer {{token}}

###
# Create a team
POST http://localhost:3030/api/team
Content-Type: application/json
Authorization: Bearer {{token}}

{
	"clubId": 1,
	"sportId": 1,
	"name": "Feminino infantil",
	"gender": "FEMALE",
	"category": "Infantil",
	"active": true	
}

###
# Update a team
PUT http://localhost:3030/api/team/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
	"sportId": 1,
	"name": "Adulto Feminino",
	"description": "Time feminino adulto de Futebol Americano",
	"image": null,
	"gender": "FEMALE",
	"category": "Adulto",
	"active": true

}

###
# Delete a team
DELETE http://localhost:3030/api/team/4
Authorization: Bearer {{token}}
