### Get User Logged
GET http://localhost:3030/api/user
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNGZ0dXdEFSUmVPVEpuZk1wMHd3ZCJ9.eyJpc3MiOiJodHRwczovL2NsdWJlcm8udXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDY4ZjI1Yjg4M2E1NjcwNWViYmM0MGI5YyIsImF1ZCI6WyJjbHViZXJvLWFwaSIsImh0dHBzOi8vY2x1YmVyby51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzYxODQ0OTczLCJleHAiOjE3NjE5MzEzNzMsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhenAiOiIydjNPcDdNMW9oZDJDU0xHaXkxd3YwUDdlRnpJc2JrWSIsInBlcm1pc3Npb25zIjpbImNyZWF0ZTpjbHViIiwicmVhZDpjbHViIiwidXBkYXRlOmNsdWIiXX0.COV5bsfy-p2q6tkwMO2lAPaMEODkJeumgEX1ej0SVnuISgtKaOOBnmJLVLq318fwbOKbv7tMzXqdSQlP_7ypt1ERr7JFf22xrf2HOrl_TChtsVXIizPk8R2pKdVtbXlH5j51_FMg1Zj4BsgpZf9K7usUC7XifB2DR7kbMPugQgdrwf1SVBgWByZvg0aznBahiZeumJfL10MGlg7zjI5qtQQkn_YoZvMB07Opxp4jtkFsngQ-bh1uJP-p8vs08HA79MPdRMbHBiKz-mWOK_DeRIROp7P40BTiD1GX0AIWI_FK30fczJ_WEtUegxHlRaNozpQdpQXJeuFKC0CQ1oPeWQ
Content-Type: application/json



### Update user by ID
PUT http://localhost:3030/api/user
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNGZ0dXdEFSUmVPVEpuZk1wMHd3ZCJ9.eyJpc3MiOiJodHRwczovL2NsdWJlcm8udXMuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDY4ZjI1Yjg4M2E1NjcwNWViYmM0MGI5YyIsImF1ZCI6WyJjbHViZXJvLWFwaSIsImh0dHBzOi8vY2x1YmVyby51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzYwNzE2ODY5LCJleHAiOjE3NjA4MDMyNjksInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJhenAiOiIydjNPcDdNMW9oZDJDU0xHaXkxd3YwUDdlRnpJc2JrWSJ9.GDUXzM3trgDxh-CSzM64JBgLzL9Cgyp_LGFod5Kn4oV-oum4zkS-Q5bk5LrPjCPIhpuRmy0ZO_RcoWQewlVRMEPfbbvPN6LDEIc8sHPfT7MGTBsk3BjxxlVX0mmFubJz02vK_fmvxpkV1r_APxHg0UZs6PMk0gy17gCWjLXQZTl-tgeG9wjRXGWmWSQBC7SCw808eYZbV4oadocl3UFNrQXW0cVWvMNJ5PBAYohwiqtE6v1wBiWJW6sgkE2HQQUFir1va_UtVWUtJUOFHQscJ0LR_f444AIx7DGrknOXzowgE0aonFxDfjYs-nIoTJmuVt9x-e_Ws-81PFrGw5n95Q
Content-Type: application/json

{ 
	"name": "Leonardo Testa",
	"nickname": "TheOvniBoss" ,
	"user_metadata": { 
		"birthDate": "1981-04-22"
	}
}
