### Get all clubs
GET http://localhost:3030/api/clubs 

### Get user by ID
GET http://localhost:3030/api/clubs/3 

### Create a new user
POST http://localhost:3030/api/clubs
Content-Type: application/json

{
    "name": "Clubero FC",
    "description": "El mejor club del mundo",
    "image": "https://clubero.com/logo.png",
    "country": "Argentina",
    "state": "Buenos Aires",
    "city": "La Plata",
    "founded": "1901-01-01",
    "active": true,
    "createdby": 1
}

### Update user by ID
PUT http://localhost:3030/api/clubs/1
Content-Type: application/json

{
    "name": "Crimson Fox",
    "description": "El mejor club del mundo",
    "image": "https://clubero.com/logo.png",
    "country": "Brasil",
    "state": "São Paulo",
    "city": "São Paulo",
    "founded": "2017-01-01",
    "active": true,
    "updatedby": 1
}


### Delete user by ID
DELETE http://localhost:3030/api/clubs/3
