## Get all sports
GET http://localhost:3030/api/sports

### Get sport by ID
GET http://localhost:3030/api/sports/1

### Create a new sport
POST http://localhost:3030/api/sports
Content-Type: application/json

{
    "name": "Futebol Americano",
    "image": "http://example.com/soccer.png"
}

### Update sport by ID
PUT http://localhost:3030/api/sports/3  
Content-Type: application/json

{
    "name": "Futebol",
    "image": "http://example.com/flagfootball.png"
}

### Delete sport by ID
DELETE http://localhost:3030/api/sports/4
