### Get all teams
GET http://localhost:3030/api/teams 

### Get team by ID
GET http://localhost:3030/api/teams/2

### Create a new team
POST http://localhost:3030/api/teams
Content-Type: application/json

{
    "clubid": 1,
    "sportid": 1,
    "name": "Equipe Princial",
    "description": "",
    "image": "http://example.com/image.png",
    "gender": "Male",
    "category": "Adulto",
    "active": true,
    "createdby": 1
}

### Update team by ID
PUT http://localhost:3030/api/teams/2
Content-Type: application/json

{
    "clubid": 1,
    "sportid": 1,
    "name": "Team A Updated",
    "description": "This is Team A Updated",
    "image": "http://example.com/image_updated.png",
    "gender": "Female",
    "category": "Youth",    
    "active": false,
    "updatedby": 1
}

### Delete team by ID
DELETE http://localhost:3030/api/teams/2   
