### Get all users
GET http://localhost:3030/api/users 

### Get user by ID
GET http://localhost:3030/api/users/1 

### Create a new user
POST http://localhost:3030/api/users
Content-Type: application/json

{
	"email": "cluberoapp@gmail.com",
	"password": "uga@12buga",
	"firstname": "Leonardo",
	"lastname": "Gerasimenko",
	"dateofbirth": "1981-04-22",
	"identifyproviderid": "0000000-0000-0000-0000-000000000001"	
}

### Update user by ID
PUT http://localhost:3030/api/users/1
Content-Type: application/json

{
	"email": "clubero@gmail.com",
	"password": "uga@12buga",
	"firstname": "Leonardo",
	"lastname": "Testa",
	"dateofbirth": "1981-04-22",
	"identifyproviderid": "0000000-0000-0000-0000-000000000000"	
}

### Delete user by ID
DELETE http://localhost:3030/api/users/4
